#pragma once
#include "main.h"
void liftSet(int power);
void driveSet(int Lpower, int Rpower);
void liftTo(int pos);
void liftTask(void *parameter);
void driveTo(float targetPosition, int power);
void driveToNoFix(float targetPosition, int power);
void driveInch(float inches, int power);
void driveInchNoFix(float inches, int power);
Gyro gyro;
Encoder lencoder;
Encoder rencoder;
void stopAllPeriodic(void);
void turn(float degrees, int power);
void turnTo(float degrees, int power);
void liftToTask(void *parameter);
void timerReset(int number);
unsigned long timer(int number);
unsigned long startTimes[12];
void lcdDisplayTime(void *parameter);
int driveMotorList[6];
int liftMotorList[6];
void stopAfter(void *milliseconds);
void gyroResetAfter(void *milliseconds);
void stopDriveAfter(void *milliseconds);
void driveStop(void);
void jerk(void);
Mutex potMutex;
int *arr;
const char* uptown[3];
void hard_reset(void);
void printButtons(void *parameter);
TaskHandle motorsSafe;
TaskHandle showTime;
TaskHandle liftToHandle;
void turnNoFix(float degrees, int power);
void driveInchAbs(float inches, int power);
void driveToAbs(float targetPosition, int power);
void smartTurn(float degrees, int power);
void smartTurnTo(float degrees, int power);
bool isLine(void);
