#include "main.h"
int OLL;
int TILLBILL;
int ORL;
int TIRLBIRL;
int BLD;
int TRD;
int isWall2;
int TLD;
int BRD;
int pot;
int potTop;
int potBottom;
int hangLockLeft;
int hangLockRight;
int hangHook;
int gyroPort;
int rencPort;
int lencPort;
int isLine;
int lineLight;
int isWall;
int liftZero;
int potHalf;
int liftToTaskPos;
int liftToTaskWait;
float inchesMultiplier;
void liftSet(int power);
void driveSet(int Lpower, int Rpower);
void liftTo(int pos);
void liftTask(void *parameter);
void driveTo(float targetPosition, int power);
void driveInch(float inches, int power);
Gyro gyro;
Encoder lencoder;
Encoder rencoder;
void stopAllPeriodic();
void turn(float degrees, int power);
void liftToTask(void *parameter);
